#!/bin/python
from os import path, getcwd
from threading import Thread
from time import sleep
from pystray import Icon, Menu, MenuItem
from PIL import Image
import autorandrbindings as autorandr

__location__ = path.realpath(path.join(getcwd(), path.dirname(__file__)))
alive = True
icon = None
last_set = None


def set_state(s: str):
    """Set the state of a profile.

    Args:
        s: The state to set the profile to

    Returns:
        A function that sets the profile state
    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """

    def inner(icon, item):
        """Sets the profile for autorandr.

        Args:
            icon: The icon to set.
            item: The item to set.
        !!! note

            The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
        """
        last_set = s
        autorandr.set_profile(s)

    return inner


def get_state(s: str):
    """Get a function that checks if the current state matches the given state.

    Args:
        s: The state to check against

    Returns:
        A function that takes an item and returns True if the current state matches the given state, False otherwise.
    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """

    def inner(item):
        """Check if the current profile is equal to the given item.

        Args:
            item: The item to compare with the current profile.

        Returns:
            True if the current profile is equal to the item, False otherwise.
        !!! note

            The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
        """
        return autorandr.current_profile() == s

    return inner


def setup_icon():
    global icon
    menu = Menu(
        lambda: (
            MenuItem(
                profile, set_state(profile), checked=get_state(profile), radio=True
            )
            for profile in autorandr.available_profiles()
        )
    )
    icon = Icon("test", Image.open(path.join(__location__, "icon.png")), menu=menu)
    return icon


def main_loop():
    global last_set
    while alive:
        sleep(60)
        cur_set = autorandr.current_profile()
        if last_set == cur_set:
            continue
        last_set = cur_set
        icon.update_menu()


def main():
    setup_icon()
    Thread(target=icon.run).start()
    main_loop()


if __name__ == "__main__":
    main()
