#!/bin/python
from subprocess import run
from typing import List


def __available_profiles__() -> List[str]:
    """!!! note

    Failed to generate docs

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    return run(
        ["autorandr", "--list"], encoding="utf-8", capture_output=True
    ).stdout.splitlines()


def available_profiles() -> List[str]:
    """!!! note

    Failed to generate docs

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    return sorted(__available_profiles__())


def set_profile(profile: str) -> None:
    """Set the profile.

    Args:
        profile: The profile to set.

    Returns:
        None

    Raises:
        ValueError: If the profile is not a registered profile.
    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    if profile in __available_profiles__():
        run(["autorandr", profile])
    else:
        raise ValueError("Profile {} is not a registered profile".format(profile))


def current_profile() -> str:
    """!!! note

    Failed to generate docs

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    return __available_profiles__()[0]
